### ISSUE TITLE
A couple of suggestions

### ISSUE THREAD

**Issue by 40days** [Hamuko/cum#12]
First of all, great job with this, it makes my life easier, but I do have a couple of suggestions

1. I think "get" should work with both individual chapters and complete mangas, similar to "follow --download".
![screenshot from 2015-11-06 13-50-46](https://cloud.githubusercontent.com/assets/11399133/10998511/7652dc5c-848d-11e5-8f49-94c8bfc3dbe2.png)
2. Allow the use of the flag --folder when using any command that involves downloads, but specially "follow", something like pic related. Something similar with "alias" would be great too!
![screenshot from 2015-11-06 13-52-55](https://cloud.githubusercontent.com/assets/11399133/10998546/bdeab940-848d-11e5-9012-ca285b11f91c.png)

Thank you for your attention and thank you for your work!

**Comment by Hamuko** [comment]
I'll try to take a look at those points at some point, maybe even for the next release. But I still have a bit of work to get Batoto scraping working again.

**Comment by Hamuko** [comment]
I added series support for `cum get` as per your first request.

The second request requires modifying the database model, so I have to build additional support for database verification in order to implement that feature nicely. Therefore I'm probably going to leave it hanging until the next version, since I'm probably going to be busy for some weeks now.

**Comment by Hamuko** [comment]
Added the second request in 8e98f5e06381903a328726a5d8e6de270dcb281b and it'll be in v0.4.
