### ISSUE TITLE
Batoto login error

### ISSUE THREAD

**Issue by abduct** [Hamuko/cum#29]
I was logged into Bato.to via the web browser, and I set my username/password in cum and all worked well.

I assume my session expired (it has been a week or so since I last visited boto.to or used cum) as I was logged out on my browser and cum was receiving a "Batoto login error" message

```
cum update
==> Updating 3 series
  [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]  3/3
==> Unable to update dead-tube (Batoto login error)
==> Unable to update suicide-island (Batoto login error)
==> Unable to update trash (Batoto login error)
```

I resolved this by setting the password hash to an empty string and re-logging into bato.to via the web browser (I don't know if this would effect it at all cause I would imagine you have your own web kit for handling cookies and sessions):

`cum config set batoto.pass_hash ""`

and running the update again successfully grabbed the latest chapters.

Perhaps cum is missing a check somewhere to re-login or generate new cookies/session data once a session has expired.

**Comment by Hamuko** [comment]
I added some code in [`batoto-login-fix`](https://github.com/Hamuko/cum/tree/batoto-login-fix) to perform a login if the registration notice is up on a series page when we scrape it. This is however limited to once per session, especially since Batoto might temp ban you if you try to log in with the wrong password too many times.

Please test out the branch before I merge it to master.

**Comment by abduct** [comment]
Alright I'll pull the test branch. It may take a while to reproduce the error since it depends on batoto terminating the session. I'll report back.

**Comment by Hamuko** [comment]
The fix branch + additional Batoto login fix has now been merged to master. Open up a new issue if you discover the fix breaking.
