### ISSUE TITLE
Malformed file exceptions for jpeg

### ISSUE THREAD

**Issue by abduct** [Hamuko/cum#37]
I've noticed this on a few series and I simply batch renamed them myself without thinking about it, but I've noticed that the "jpeg" extension gets saved to the zip archive as "jpe" as shown here:

http://i.imgur.com/k49OJSg.png

The effected manga chapter is "DEAD Tube - c027 [Yo Manga]" I believe from the batoto source.

Just a minor thing, the images are not corrupted or anything, just being saved with the wrong extension. 

Edit:: I guess JPE is a new extension that my reader doesn't recognize, but seems weird that you wouldn't use the source file extension of "jpg". Either way just letting you know.

**Comment by Hamuko** [comment]
The source of the file extension currently comes from `guess_extension(r.headers.get('content-type'))`, which seems to return .jpe quite often for JPEG data, which is as valid of an extension as .jpeg and .jpg.

This has been a noticed behavior of the `guess_extension()` function, but it has never been corrected since it has worked just fine. While I guess I should fix it to a more common format, the main issue here is with your reader.
